server: 
  display-name: ${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}
  address: ${HOSTNAME:localhost.shinigami.io}
  port: ${VPORT:1234}
  context-path: /
spring:
  profiles:
    active: local
ribbon:
  eureka:
    enabled: false
eureka:
  client:
    enabled: false